name: Tag and Release
on:
  push:
    branches: main

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tag and Release
        id: tag_release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
